name: TrainingPlugin
version: '${version}'
main: ru.healthanmary.trainingplugin.TrainingPlugin
api-version: '1.16'
authors: [healthanmary]
commands:
  effectmenu:
    aliases: em
  standspawn:
    aliases: ss
  getchestplate:
    aliases: gch
  getbook:
    aliases: gbk
